jobs:
  type_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: yarn tsc

name: Type Check

on:
  pull_request: ~
  push:
    branches:
      - main
